### PR TITLE
script to validate output fr last deterministic sc3 step against reference

### PR DESCRIPTION
**Pull request by jlchang**
per Vlad, script for validation of docker image. Wrapper script for sc3 wrapper function to follow.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
Thanks for this PR too @jlchang . Could you remove the sc3-sc3.R which is PR'd separately via https://github.com/ebi-gene-expression-group/bioconductor-sc3-scripts/pull/18 please?

**Comment by jlchang** [comment]
Oops, removed sc3-sc3.R from the validation branch.

**Review by pinin4fjords — APPROVED** [review]
Looks good - and I've checked that the script works

**Comment by nh3** [comment]
Hi @jlchang, I recently found that sc3-sc3-validate.R gives inconsistent validation [results](https://travis-ci.org/ebi-gene-expression-group/bioconductor-sc3-scripts/builds). Basically, the same commit [bc08676](https://github.com/ebi-gene-expression-group/bioconductor-sc3-scripts/commit/bc086763b187414125f686d14eea9befa231e0fc) sometimes passed sometimes failed. As I tested locally (in a conda environment with sc3 1.8.0, just run ./sc3-sc3-validate.R) I always get a fail for the same reason:
"Error: Validation failed - max relative error exceeds threshold", and it's always due to one particular column (V6 below):

```
> obs <- as.matrix(read.csv('validation_output.csv', header=F)[,-1])
> ref <- as.matrix(read.csv('reference.csv', header=F)[,-1])
> summary(abs(obs - ref))
       V2                  V3                  V4           
 Min.   :0.000e+00   Min.   :0.000e+00   Min.   :0.000e+00  
 1st Qu.:0.000e+00   1st Qu.:4.025e-16   1st Qu.:9.714e-17  
 Median :0.000e+00   Median :9.992e-16   Median :2.082e-16  
 Mean   :1.339e-17   Mean   :1.173e-15   Mean   :2.933e-16  
 3rd Qu.:0.000e+00   3rd Qu.:1.596e-15   3rd Qu.:4.025e-16  
 Max.   :1.110e-16   Max.   :1.754e-14   Max.   :1.499e-15  
       V5                  V6                  V7           
 Min.   :0.000e+00   Min.   :0.0001939   Min.   :0.000e+00  
 1st Qu.:3.999e-15   1st Qu.:0.0341834   1st Qu.:3.202e-15  
 Median :8.979e-15   Median :0.0628960   Median :6.202e-15  
 Mean   :1.285e-14   Mean   :0.0945638   Mean   :8.849e-15  
 3rd Qu.:2.020e-14   3rd Qu.:0.1517274   3rd Qu.:1.243e-14  
 Max.   :7.100e-14   Max.   :0.2961647   Max.   :1.364e-13  
       V8                  V9                 V10           
 Min.   :0.000e+00   Min.   :7.026e-17   Min.   :3.990e-16  
 1st Qu.:3.106e-15   1st Qu.:8.200e-15   1st Qu.:6.501e-15  
 Median :6.349e-15   Median :1.564e-14   Median :1.400e-14  
 Mean   :8.589e-15   Mean   :2.296e-14   Mean   :1.933e-14  
 3rd Qu.:1.157e-14   3rd Qu.:3.008e-14   3rd Qu.:2.632e-14  
 Max.   :1.086e-13   Max.   :3.107e-13   Max.   :3.095e-13  
      V11                 V12                 V13           
 Min.   :4.007e-16   Min.   :3.504e-16   Min.   :0.000e+00  
 1st Qu.:8.651e-15   1st Qu.:2.219e-14   1st Qu.:1.740e-14  
 Median :1.720e-14   Median :4.392e-14   Median :3.865e-14  
 Mean   :2.908e-14   Mean   :6.777e-14   Mean   :5.447e-14  
 3rd Qu.:3.330e-14   3rd Qu.:8.907e-14   3rd Qu.:6.890e-14  
 Max.   :3.680e-13   Max.   :4.510e-13   Max.   :4.980e-13  
      V14                 V15                 V16           
 Min.   :1.201e-16   Min.   :8.986e-16   Min.   :1.100e-15  
 1st Qu.:4.471e-14   1st Qu.:4.815e-14   1st Qu.:4.104e-14  
 Median :9.126e-14   Median :1.008e-13   Median :9.266e-14  
 Mean   :1.282e-13   Mean   :1.439e-13   Mean   :1.377e-13  
 3rd Qu.:1.657e-13   3rd Qu.:1.929e-13   3rd Qu.:1.525e-13  
 Max.   :2.238e-12   Max.   :1.174e-12   Max.   :2.455e-12  
      V17                 V18                 V19           
 Min.   :9.001e-16   Min.   :0.000e+00   Min.   :3.018e-16  
 1st Qu.:2.020e-14   1st Qu.:2.755e-14   1st Qu.:2.195e-14  
 Median :4.801e-14   Median :6.181e-14   Median :4.240e-14  
 Mean   :7.872e-14   Mean   :1.030e-13   Mean   :6.651e-14  
 3rd Qu.:9.032e-14   3rd Qu.:1.263e-13   3rd Qu.:7.683e-14  
 Max.   :7.240e-13   Max.   :1.607e-12   Max.   :8.000e-13  
      V20           
 Min.   :3.001e-16  
 1st Qu.:3.107e-14  
 Median :6.862e-14  
 Mean   :1.084e-13  
 3rd Qu.:1.322e-13  
 Max.   :8.030e-13 
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS/LAPACK: /Users/nh3/miniconda2/envs/__bioconductor-sc3@1.8.0/lib/R/lib/libRblas.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SingleCellExperiment_1.2.0  SummarizedExperiment_1.10.1
 [3] DelayedArray_0.6.6          BiocParallel_1.14.2        
 [5] matrixStats_0.54.0          Biobase_2.40.0             
 [7] GenomicRanges_1.32.7        GenomeInfoDb_1.16.0        
 [9] IRanges_2.14.12             S4Vectors_0.18.3           
[11] BiocGenerics_0.26.0         SC3_1.8.0                  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1             mvtnorm_1.0-10         lattice_0.20-38       
 [4] class_7.3-15           gtools_3.8.1           digest_0.6.18         
 [7] foreach_1.4.4          mime_0.6               R6_2.4.0              
[10] plyr_1.8.4             WriteXLS_4.1.0         pcaPP_1.9-73          
[13] e1071_1.7-0            ggplot2_3.1.0          pillar_1.3.1          
[16] gplots_3.0.1.1         zlibbioc_1.26.0        rlang_0.3.1           
[19] lazyeval_0.2.2         gdata_2.18.0           Matrix_1.2-16         
[22] stringr_1.4.0          pheatmap_1.0.12        RCurl_1.95-4.12       
[25] munsell_0.5.0          shiny_1.2.0            httpuv_1.4.5.1        
[28] compiler_3.5.1         pkgconfig_2.0.2        pkgmaker_0.27         
[31] htmltools_0.3.6        tibble_2.1.1           GenomeInfoDbData_1.2.0
[34] codetools_0.2-16       later_0.8.0            crayon_1.3.4          
[37] rrcov_1.4-4            withr_2.1.2            bitops_1.0-6          
[40] grid_3.5.1             xtable_1.8-3           gtable_0.2.0          
[43] registry_0.5           magrittr_1.5           scales_1.0.0          
[46] bibtex_0.4.2           KernSmooth_2.23-15     stringi_1.4.3         
[49] XVector_0.20.0         ROCR_1.0-7             promises_1.0.1        
[52] doRNG_1.7.1            doParallel_1.0.14      robustbase_0.93-2     
[55] RColorBrewer_1.1-2     iterators_1.0.10       tools_3.5.1           
[58] DEoptimR_1.0-8         rngtools_1.3.1         colorspace_1.4-0      
[61] cluster_2.0.7-1        caTools_1.17.1.2 
```
I also tried a different version of sc3 (1.10.0) locally which gives exactly the same output (and error). Below is the sessionInfo()
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS/LAPACK: /Users/nh3/miniconda2/envs/r35/lib/R/lib/libRblas.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SingleCellExperiment_1.4.0  SummarizedExperiment_1.12.0
 [3] DelayedArray_0.8.0          BiocParallel_1.16.2        
 [5] matrixStats_0.54.0          Biobase_2.42.0             
 [7] GenomicRanges_1.34.0        GenomeInfoDb_1.18.1        
 [9] IRanges_2.16.0              S4Vectors_0.20.1           
[11] BiocGenerics_0.28.0         SC3_1.10.0                 

loaded via a namespace (and not attached):
 [1] foreach_1.4.4          gtools_3.8.1           shiny_1.2.0           
 [4] assertthat_0.2.0       doRNG_1.7.1            GenomeInfoDbData_1.2.0
 [7] robustbase_0.93-2      pillar_1.3.1           lattice_0.20-38       
[10] glue_1.3.1             digest_0.6.18          RColorBrewer_1.1-2    
[13] promises_1.0.1         XVector_0.22.0         colorspace_1.4-0      
[16] htmltools_0.3.6        httpuv_1.4.5.1         Matrix_1.2-16         
[19] plyr_1.8.4             pcaPP_1.9-73           WriteXLS_4.1.0        
[22] pkgconfig_2.0.2        bibtex_0.4.2           pheatmap_1.0.12       
[25] zlibbioc_1.28.0        purrr_0.3.2            xtable_1.8-3          
[28] mvtnorm_1.0-8          scales_1.0.0           gdata_2.18.0          
[31] later_0.8.0            tibble_2.1.1           pkgmaker_0.27         
[34] ggplot2_3.1.0          withr_2.1.2            ROCR_1.0-7            
[37] lazyeval_0.2.2         magrittr_1.5           crayon_1.3.4          
[40] mime_0.6               doParallel_1.0.14      gplots_3.0.1.1        
[43] class_7.3-15           tools_3.5.1            registry_0.5          
[46] stringr_1.4.0          munsell_0.5.0          cluster_2.0.7-1       
[49] rngtools_1.3.1         compiler_3.5.1         e1071_1.7-0           
[52] caTools_1.17.1.2       rlang_0.3.1            grid_3.5.1            
[55] RCurl_1.95-4.12        iterators_1.0.10       bitops_1.0-6          
[58] gtable_0.2.0           codetools_0.2-16       rrcov_1.4-4           
[61] R6_2.4.0               dplyr_0.8.0.1          KernSmooth_2.23-15    
[64] stringi_1.4.3          Rcpp_1.0.1             DEoptimR_1.0-8        
[67] tidyselect_0.2.5
```

As the script depends only on sc3 and nothing we develop, I suspect it might have something to do to the version of sc3 and/or the version of sc3's dependencies.

Do you have any insights into this? Thanks!

**Comment by jlchang** [comment]
Hi @nh3,

Thanks for bringing this unexpected behavior to my attention. Is there a docker container that reproduces this behavior so I can examine the issue on my end? If not, I'll see if I can replicate the issue on my mac.

Would you still have validation_output.csv and reference.csv available from those failures? Could you send them to me? Thanks!

**Comment by jlchang** [comment]
@nh3 
On my mac, iterations of sc3-sc3-validate.R generate the exact same output and that output passes validation against the reference (The reference data was generated by Vlad. Sadly, I do not have sessionInfo from when the reference data was generated).

Using data generated by the methodologist as the reference, the previous and current docker containers generate data that is all within 1.0e-8 of the reference data. I'm not sure what might be causing your local installation to fall outside of those bounds... I agree that it seems likely a differing SC3 dependency may causing the issue. 

Here's sessionInfo from my mac, in case this helps identify the underlying issue:
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] SC3_1.8.0                   BiocInstaller_1.30.0       
 [3] SingleCellExperiment_1.2.0  SummarizedExperiment_1.10.1
 [5] DelayedArray_0.6.6          BiocParallel_1.14.2        
 [7] matrixStats_0.54.0          Biobase_2.40.0             
 [9] GenomicRanges_1.32.7        GenomeInfoDb_1.16.0        
[11] IRanges_2.14.12             S4Vectors_0.18.3           
[13] BiocGenerics_0.26.0        

loaded via a namespace (and not attached):
 [1] foreach_1.4.4          gtools_3.8.1           shiny_1.2.0           
 [4] assertthat_0.2.0       doRNG_1.7.1            GenomeInfoDbData_1.1.0
 [7] robustbase_0.93-3      pillar_1.3.0           lattice_0.20-35       
[10] glue_1.3.0             digest_0.6.18          promises_1.0.1        
[13] RColorBrewer_1.1-2     XVector_0.20.0         colorspace_1.3-2      
[16] htmltools_0.3.6        httpuv_1.4.5.1         Matrix_1.2-14         
[19] plyr_1.8.4             pcaPP_1.9-73           WriteXLS_4.1.0        
[22] pkgconfig_2.0.2        bibtex_0.4.2           pheatmap_1.0.12       
[25] zlibbioc_1.26.0        purrr_0.2.5            xtable_1.8-3          
[28] mvtnorm_1.0-8          scales_1.0.0           gdata_2.18.0          
[31] later_0.7.5            tibble_1.4.2           pkgmaker_0.27         
[34] ggplot2_3.1.0          withr_2.1.2            ROCR_1.0-7            
[37] lazyeval_0.2.1         mime_0.6               magrittr_1.5          
[40] crayon_1.3.4           doParallel_1.0.14      gplots_3.0.1.1        
[43] class_7.3-14           tools_3.5.1            registry_0.5          
[46] stringr_1.3.1          munsell_0.5.0          cluster_2.0.7-1       
[49] rngtools_1.3.1         bindrcpp_0.2.2         compiler_3.5.1        
[52] e1071_1.7-0.1          caTools_1.17.1.1       rlang_0.3.0.1         
[55] grid_3.5.1             RCurl_1.95-4.11        iterators_1.0.10      
[58] bitops_1.0-6           gtable_0.2.0           codetools_0.2-15      
[61] rrcov_1.4-7            R6_2.3.0               dplyr_0.7.8           
[64] bindr_0.1.1            KernSmooth_2.23-15     stringi_1.2.4         
[67] Rcpp_1.0.0             DEoptimR_1.0-8         tidyselect_0.2.5

**Comment by nh3** [comment]
Hi @jlchang, I've put the generated validation_output.csv and reference.csv at this [link](https://drive.google.com/drive/folders/1ktmxYL3UMgq8VJvEW-GpcOGwdy232OHE?usp=sharing).

The online travis CI tests were containerised, but not sure if you can download them.

My local test was based on conda. So basically with the following the channel priority (from high to low): `conda-forge, bioconda, defaults`, and use `conda create -n sc3 bioconductor-sc3=1.8.0` (or `=1.10.0`) should get you a test environment similar to, if not the same as, mine.

**Pull request merged**
