### PR TITLE
Change clusters output to a single file

### PR DESCRIPTION
**Pull request by pinin4fjords**
There you go @nh3 - clusters output to a single file.

### CODE REVIEW

**Comment by pinin4fjords** [comment]
ping @nh3

**Review by nh3 — APPROVED** [review]
LGTM. Thanks @pinin4fjords !

**Comment by pinin4fjords** [comment]
Thanks @nh3 . Are you done with tweaks to this package? Should I release so these changes become available in the conda package?

**Comment by nh3** [comment]
There's introspective message to be printed...

**Comment by pinin4fjords** [comment]
Okay, I'll hold off then. Maybe that needs to be a story prioritised for our sprint today.

**Pull request merged**
